version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: zaman_ai_assistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - OPENAI_API_KEY=sk-roG3OusRr0TLCHAADks6lw
      - OPENAI_BASE_URL=https://openai-hub.neuraldeep.tech
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
