spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zaman_ai_assistant_dev
    username: postgres
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.zamanbank.aiassistant: DEBUG
    org.springframework.ai: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
