spring:
  application:
    name: zaman-ai-assistant
  
  datasource:
    url: jdbc:postgresql://localhost:5432/zaman_ai_assistant
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}

# AI Configuration
ai:
  openai:
    api-key: ${OPENAI_API_KEY:sk-roG3OusRr0TLCHAADks6lw}
    base-url: ${OPENAI_BASE_URL:https://openai-hub.neuraldeep.tech}
    model: gpt-4o-mini
    temperature: 0.7
    max-tokens: 1000

# Server Configuration
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

# Logging
logging:
  level:
    com.zamanbank.aiassistant: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
